limit_req_zone $binary_remote_addr zone=api:10m rate=1000r/s;

server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    charset utf-8;

    error_page 429 @rate_limit_response;
    location @rate_limit_response {
        default_type application/json;
        return 429 '{"message":"Too many requests","status":429}';
    }

    location / {
        root /usr/share/nginx/html/public;
        index  index.php index.html index.htm;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    location ~ \.php$ {
       limit_req zone=api burst=200 nodelay;
       limit_req_status 429;
       root           /var/www/html/public;
       fastcgi_pass   php:9000;
       fastcgi_index  index.php;
       fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
       fastcgi_intercept_errors on;
       include        fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

